export const ENEMY_SIZES = {
  CIRCLE_RADIUS: 18,
  SENSING_CIRCLE_RADIUS: 100,
  ATTACKING_DISTANCE: 30,
};

export const ENEMY_BITE_FREQUENCY_MS = 700;

export const PLAYER_SIZES = {
  CIRCLE_RADIUS: 10,
  SENSING_CIRCLE_RADIUS: 10,
  ATTACKING_DISTANCE: 30,
};

export const DROP_ITEM_SIZES = {
  CIRCLE_RADIUS: 9,
  SENSING_CIRCLE_RADIUS: 9,
  ATTACKING_DISTANCE: 9,
};

export const RESOURCE_SIZES = {
  CIRCLE_RADIUS: 15,
  SENSING_CIRCLE_RADIUS: 19,
  ATTACKING_DISTANCE: 19,
};
